#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  upperLeftSonar, sensorSONAR_mm)
#pragma config(Sensor, dgtl3,  lowerLeftSonar, sensorSONAR_mm)
#pragma config(Sensor, dgtl5,  upperRightSonar, sensorSONAR_mm)
#pragma config(Sensor, dgtl7,  lowerRightSonar, sensorSONAR_mm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           frontRightMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port3,           backRightMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port4,           frontLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           backLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int WALL_DISTANCE = 200;

void drive(int power = 127, int direction = 1, bool lateral = false)
{
      if (lateral) //Drive Left or Right
      {
            motor[frontRightMotor]  =     power *    direction;
            motor[frontLeftMotor]   =     power *    direction;
            motor[backRightMotor]   =     power *   -direction;
            motor[backLeftMotor]    =     power *   -direction;
      }
      else        //Drive foward or backward
      {
    	 	motor[frontRightMotor]  =     power *  direction;
    	    motor[frontLeftMotor]   =     power * -direction;
    	    motor[backRightMotor]   =     power *  direction;
    	    motor[backLeftMotor]    =     power * -direction;
      }
}

void turn(int power = 127, int direction = 1)
{
    motor[frontRightMotor]  =     power *    -direction;
    motor[frontLeftMotor]   =     power *    -direction;
    motor[backRightMotor]   =     power *    -direction;
    motor[backLeftMotor]    =     power *    -direction;
}

void turnMeasure(int angle)
{
		SensorValue[gyro] = 0;
}

bool wallCheck()
{
	bool checkResult = false;
	if (sensorValue(upperLeftSonar) < WALL_DISTANCE && sensorVAlue(upperRightSonar) < WALL_DISTANCE)
 	{		//Uppers Sensors detect Walls
		checkResult = True;
	}
	else if (sensorValue(lowerLeftSonar) < WALL_DISTANCE && sensorVAlue(lowerRightSonar) < WALL_DISTANCE)
 	{		//Lower Sensors detect Walss
		checkResult = True;
	}
	return checkResult;
}

void angleCompensation(int num)
{

}

task main()
{
   //Calibrate the gyro sensor
	SensorType[gyro] = sensorNone;
	wait1Msec(1000);
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);

	while(true)
	{
			//Drive Function Paramters are int Power, int Direction, bool lateral
		if (vexRT[Btn7U])
	    {
	        drive(127,1);
	  	}
	  	else if (vexRT[Btn7D])
	    {
	        drive(127,-1);
	  	}
	  	else if (vexRT[Btn7L])
	    {
	        drive(127,1,True);
	  	}
	  	else if (vexRT[Btn7R])
	    {
	        drive(127,-1,True);
	  	}
	  	else if (vexRT[Btn6U])
	    {//Turn Right
	        turn(127,1);
	  	}
	  	else if (vexRT[Btn5U])
	    {//Turn Left
	        turn(127,-1);
	  	}
	  	else if (vexRT[Btn8U] && !wallCheck())
	    {
	        drive(127,1);
	  	}
	  	else
		  {
					drive(0);
		  }
	 }
}
