#pragma config(Motor,  port1,           frontLeftMotor, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           backLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          frontRightMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(int flm, int blm, int frm, int brm)
{
		motor[frontLeftMotor]  =  flm;
		motor[backLeftMotor]   = 	blm;
		motor[frontRightMotor] =  frm;
		motor[backRightMotor]  =  brm;
}


task main()
{
		while(true)
		{
				drive(vexRT[ch3],vexRT[ch1],-vexRT[ch3],vexRT[ch1]);

		}

}
