#pragma config(Motor,  port1,           neutralDrive,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           lights1,       tmotorNone, openLoop)
#pragma config(Motor,  port9,           lights2,       tmotorNone, openLoop)
#pragma config(Motor,  port10,          turnDrive,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int MAX_POW  = 127;
const int LOW_POW  = 75;

void driveControl(int power){
		motor[neutralDrive] = power;
}

void turnControl(int direction){
		motor[turnDrive] = direction;
}

void turnFlow(){
		if (VexRT[btn5U]){ //fast turn left
				turnControl(-MAX_POW);
		}
		else if (VexRT[btn6U]){ //fast turn right
				turnControl(MAX_POW);
		}
		else if (VexRT[btn5D]){ //slow turn left
				turnControl(-LOW_POW);
		}
		else if (VexRT[btn6D]){ //slow turn right
				turnControl(LOW_POW);
		}
}

void driveFlow(){
	  if(VexRT[btn7U]){ //fast drive foward
	  		driveControl(MAX_POW);
		}
		else if(VexRT[btn7D]){ //fast drive foward
	  		driveControl(-MAX_POW);
		}

}


task main(){
		while true{
				turnFlow();
				driveFlow();
		}
}
