#pragma config(Motor,  port2,           backRightDriveF, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRightDriveE, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRightDriveD, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           frontLeftDriveC, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           frontLeftDriveB, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           frontLeftDriveA, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int turnSpd = 120;
int turn;


void topLeftDrive(int power){
		power = -power;
		motor(frontLeftDriveA) = power;
		motor(frontLeftDriveB) = power;
		motor(frontLeftDriveC) = power;
}

void backRightDrive(int power){
		motor(backRightDriveD) = power;
		motor(backRightDriveE) = power;
		motor(backRightDriveF) = power;
}

void drive(int speed, int turn, int strafe) {
	  //speed  = -speed;    //reverse speed until ports are rearranged
		//strafe = -strafe;   //reverse strafe until ports are rearranged
	  //motor(leftFrontDrive) = speed + turn + strafe;
		//motor(leftBackDrive) = speed + turn - strafe;
		//motor(rightFrontDrive) = speed - turn - strafe;
		//motor(rightBackDrive) = speed - turn + strafe;

		topLeftDrive(speed + turn + strafe);
		backRightDrive(speed - turn + strafe);
}

task main() {

		while(true){
				int speed = (abs(vexRT(Ch3))<20)?0: vexRT(Ch3);
			  int turn = (abs(vexRT(Ch1))<20)?0: vexRT(Ch1);
				int strafe = (abs(vexRT(Ch4))<20)?0: vexRT(Ch4);
				/*
				if (vexRT(btn8L) || vexRT(btn8R)){
						if (vexRT(btn8L)) {
								turn = -turnSpd;
						}
						else if (vexRT(btn8R)){
								turn = turnSpd;
						}
				}
				else {
						turn = 0;
				}
				*/
				drive(speed,turn,strafe);
		}
}
